### ISSUE TITLE
[SUPPORT/QUESTION] Issues with Applying Backdrop Blur Filter Alongside Border Radius

### ISSUE THREAD

**Issue by yiruzu** [overextended/ox_inventory#1680]
I'm having trouble getting the backdrop blur filter to work with border-radius in CSS. The blur effect is not following the rounded corners set by border-radius, making the element's background blur uniformly across its entire area. How can I make the blur effect adhere to the element's curved edges?

![image](https://github.com/overextended/ox_inventory/assets/94981325/2e74d4b0-feb5-476f-96ca-90681d604d33)

```CSS
.context-menu-list {
  color: #fff;
  background-color: rgba(10, 10, 10, 0.25);
  backdrop-filter: blur(10px);
  min-width: 100px;
  padding: 4px;
  border-color: #0003;
  border-style: inset;
  border-width: 1px;
  border-radius: 10px;
  outline: none;
  display: flex;
  flex-direction: column;
}
```

![image](https://github.com/overextended/ox_inventory/assets/94981325/d1e58c98-e7dd-4470-8831-0f1121d357f5)

```CSS
.tooltip-wrapper {
  pointer-events: none;
  display: flex;
  color: #fff;
  background-color: rgba(10, 10, 10, 0.25);
  backdrop-filter: blur(10px);
  width: 200px;
  padding: 8px;
  flex-direction: column;
  min-width: 200px;
  font-family: Saira;
  border-radius: 4px;
  border-color: #0003;
  border-style: inset;
  border-width: 1px;
}
```
